USE master;
GO

IF DB_ID('DATAWAREHOUSE') IS NOT NULL
BEGIN
    ALTER DATABASE DATAWAREHOUSE SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE DATAWAREHOUSE;
END;
GO

CREATE DATABASE DATAWAREHOUSE;
GO

USE DATAWAREHOUSE;
GO

CREATE SCHEMA BRONZE;
GO

CREATE SCHEMA SILVER;
GO

CREATE SCHEMA GOLD;
GO

IF OBJECT_ID ('BRONZE.CRM_CUSTOMER_INFO','U') IS NOT NULL
	DROP TABLE BRONZE.CRM_CUSTOMER_INFO;
CREATE TABLE BRONZE.CRM_CUSTOMER_INFO(
CUST_ID INT,
CUST_KEY NVARCHAR(50),
CUST_FIRSTNAME NVARCHAR(50),
CUST_LASTNAME NVARCHAR(50),
CUST_MARITALSTATUS NVARCHAR(50),
CUST_GENDER NVARCHAR(50),
CUST_CREATEDATE date
);
IF OBJECT_ID ('BRONZE.CRM_PRODUCT_INFO','U') IS NOT NULL
	DROP TABLE BRONZE.CRM_PRODUCT_INFO;
CREATE TABLE BRONZE.CRM_PRODUCT_INFO(
PRD_ID INT,
PRD_KEY NVARCHAR(50),
PRD_NAME NVARCHAR(50),
PRD_COST INT,
PRD_LINE NVARCHAR(50),
PRD_STARTDATE date,
PRD_ENDDATE date
);
IF OBJECT_ID ('BRONZE.CRM_SALES_INFO','U') IS NOT NULL
	DROP TABLE BRONZE.CRM_SALES_INFO;
CREATE TABLE BRONZE.CRM_SALES_INFO(
SLS_ORDER_NUM VARCHAR(50),
SLS_PRODUCT_KEY VARCHAR(50),
SLS_CUSTOMER_ID INT,
SLS_ORDER_DATE INT,
SLS_SHIPPING_DATE INT,
SLS_DUE_DATE INT,
SLS_SALES INT,
SLS_QUANTITY INT,
SLS_PRICE INT
); 
IF OBJECT_ID ('BRONZE.ERP_CUSTAZ12','U') IS NOT NULL
	DROP TABLE BRONZE.ERP_CUSTAZ12;
CREATE TABLE BRONZE.ERP_CUSTAZ12(
CID NVARCHAR(50),
BDATE DATE,
GENDER NVARCHAR(10)
);
IF OBJECT_ID ('BRONZE.ERP_CUST_LOCA101','U') IS NOT NULL
	DROP TABLE BRONZE.ERP_CUST_LOCA101;
CREATE TABLE BRONZE.ERP_CUST_LOCA101(
CID NVARCHAR(50),
COUNTRY NVARCHAR(50)
);

IF OBJECT_ID ('BRONZE.ERP_CUST_PX_CAT_G1V2','U') IS NOT NULL
	DROP TABLE BRONZE.ERP_CUST_PX_CAT_G1V2;
CREATE TABLE BRONZE.ERP_CUST_PX_CAT_G1V2(
ID NVARCHAR(50),
CATEGORY NVARCHAR(50),
SUB_CATEGORY NVARCHAR(50),
MAINTENANCE NVARCHAR(20)
);

GO
CREATE OR ALTER PROCEDURE BRONZE.LOAD_BRONZE AS
BEGIN
	DECLARE @STARTTIME DATETIME,@ENDTIME DATETIME;
	BEGIN TRY
		PRINT '*****************************************';
		PRINT 'LOADING BRONZE LAYER';
		PRINT '*****************************************';

		PRINT '-----------------------------------------';
		PRINT 'LOADING CRM FOLDER';
		PRINT '-----------------------------------------';
		SET @STARTTIME = GETDATE();
		PRINT  'TRUNCATING TABLE BRONZE.CRM_CUSTOMER_INFO';
		TRUNCATE TABLE BRONZE.CRM_CUSTOMER_INFO;
		PRINT 'INSERTING DATA INTO BRONZE.CRM_CUSTOMER_INFO';
		BULK INSERT BRONZE.CRM_CUSTOMER_INFO
		FROM 'C:\Users\Asus\OneDrive\Desktop\Data Science\SQL_Projects\RESOURCES\SOURCE_CRM\cust_info.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @ENDTIME = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(second,@STARTTIME,@ENDTIME) AS NVARCHAR) + ' SECONDS';

		SET @STARTTIME = GETDATE();
		PRINT  'TRUNCATING TABLE BRONZE.CRM_PRODUCT_INFO';
		TRUNCATE TABLE BRONZE.CRM_PRODUCT_INFO;
		PRINT 'INSERTING INTO BRONZE.CRM_PRODUCT_INFO';
		BULK INSERT BRONZE.CRM_PRODUCT_INFO
		FROM 'C:\Users\Asus\OneDrive\Desktop\Data Science\SQL_Projects\RESOURCES\SOURCE_CRM\prd_info.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @ENDTIME = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(SECOND,@STARTTIME,@ENDTIME) AS NVARCHAR) + ' SECONDS';


		SET @STARTTIME = GETDATE();
		PRINT  'TRUNCATING TABLE BRONZE.CRM_SALES_INFO';
		TRUNCATE TABLE BRONZE.CRM_SALES_INFO;
		PRINT'INSERTING INTO BRONZE.CRM_SALES_INFO';
		BULK INSERT BRONZE.CRM_SALES_INFO
		FROM 'C:\Users\Asus\OneDrive\Desktop\Data Science\SQL_Projects\RESOURCES\SOURCE_CRM\sales_details.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @ENDTIME = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(SECOND,@STARTTIME,@ENDTIME) AS NVARCHAR) + ' SECONDS';


		PRINT '-----------------------------------------';
		PRINT 'LOADING ERP FOLDER';
		PRINT '-----------------------------------------';


		SET @STARTTIME = GETDATE();
		PRINT  'TRUNCATING TABLE BRONZE.ERP_CUSTAZ12';
		TRUNCATE TABLE BRONZE.ERP_CUSTAZ12;
		PRINT 'INSERTING INTO BRONZE.ERP_CUSTAZ12';
		BULK INSERT BRONZE.ERP_CUSTAZ12
		FROM 'C:\Users\Asus\OneDrive\Desktop\Data Science\SQL_Projects\RESOURCES\SOURCE_ERP\CUST_AZ12.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @ENDTIME = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(SECOND,@STARTTIME,@ENDTIME) AS NVARCHAR) + ' SECONDS';

		SET @STARTTIME = GETDATE();
		PRINT  'TRUNCATING TABLE BRONZE.ERP_CUST_LOCA101';
		TRUNCATE TABLE BRONZE.ERP_CUST_LOCA101;
		PRINT 'INSERTING DATA INTO BRONZE.ERP_CUST_LOCA101'
		BULK INSERT BRONZE.ERP_CUST_LOCA101
		FROM 'C:\Users\Asus\OneDrive\Desktop\Data Science\SQL_Projects\RESOURCES\SOURCE_ERP\LOC_A101.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @ENDTIME = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(SECOND,@STARTTIME,@ENDTIME) AS NVARCHAR) + ' SECONDS';


		SET @STARTTIME = GETDATE();
		PRINT  'TRUNCATING TABLE BRONZE.ERP_CUST_PX_CAT_G1V2';
		TRUNCATE TABLE BRONZE.ERP_CUST_PX_CAT_G1V2;
		PRINT 'INSERTING INTO BRONZE.ERP_CUST_PX_CAT_G1V2';
		BULK INSERT BRONZE.ERP_CUST_PX_CAT_G1V2
		FROM 'C:\Users\Asus\OneDrive\Desktop\Data Science\SQL_Projects\RESOURCES\SOURCE_ERP\PX_CAT_G1V2.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @ENDTIME = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(SECOND,@STARTTIME,@ENDTIME) AS NVARCHAR) + ' SECONDS';


	END TRY
	BEGIN CATCH
	PRINT 'ERROR WHILE LOAADING BRONZE LAYER';
	PRINT 'ERROR = ' + ERROR_MESSAGE();
	PRINT 'ERROR NUMBER = ' + CAST  (ERROR_NUMBER() AS NVARCHAR);
	END CATCH;
	
END;
GO

EXEC BRONZE.LOAD_BRONZE;
GO
