USE master;
GO

IF DB_ID('DATAWAREHOUSE') IS NOT NULL
BEGIN
    ALTER DATABASE DATAWAREHOUSE SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE DATAWAREHOUSE;
END;
GO

CREATE DATABASE DATAWAREHOUSE;
GO

USE DATAWAREHOUSE;
GO

CREATE SCHEMA BRONZE;
GO

CREATE SCHEMA SILVER;
GO

CREATE SCHEMA GOLD;
GO

IF OBJECT_ID ('BRONZE.CRM_CUSTOMER_INFO','U') IS NOT NULL
	DROP TABLE BRONZE.CRM_CUSTOMER_INFO;
CREATE TABLE BRONZE.CRM_CUSTOMER_INFO(
CUST_ID INT,
CUST_KEY NVARCHAR(50),
CUST_FIRSTNAME NVARCHAR(50),
CUST_LASTNAME NVARCHAR(50),
CUST_MARITALSTATUS NVARCHAR(50),
CUST_GENDER NVARCHAR(50),
CUST_CREATEDATE date
);
IF OBJECT_ID ('BRONZE.CRM_PRODUCT_INFO','U') IS NOT NULL
	DROP TABLE BRONZE.CRM_PRODUCT_INFO;
CREATE TABLE BRONZE.CRM_PRODUCT_INFO(
PRD_ID INT,
PRD_KEY NVARCHAR(50),
PRD_NAME NVARCHAR(50),
PRD_COST INT,
PRD_LINE NVARCHAR(50),
PRD_STARTDATE date,
PRD_ENDDATE date
);
IF OBJECT_ID ('BRONZE.CRM_SALES_INFO','U') IS NOT NULL
	DROP TABLE BRONZE.CRM_SALES_INFO;
CREATE TABLE BRONZE.CRM_SALES_INFO(
SLS_ORDER_NUM VARCHAR(50),
SLS_PRODUCT_KEY VARCHAR(50),
SLS_CUSTOMER_ID INT,
SLS_ORDER_DATE INT,
SLS_SHIPPING_DATE INT,
SLS_DUE_DATE INT,
SLS_SALES INT,
SLS_QUANTITY INT,
SLS_PRICE INT
); 
IF OBJECT_ID ('BRONZE.ERP_CUSTAZ12','U') IS NOT NULL
	DROP TABLE BRONZE.ERP_CUSTAZ12;
CREATE TABLE BRONZE.ERP_CUSTAZ12(
CID NVARCHAR(50),
BDATE DATE,
GENDER NVARCHAR(10)
);
IF OBJECT_ID ('BRONZE.ERP_CUST_LOCA101','U') IS NOT NULL
	DROP TABLE BRONZE.ERP_CUST_LOCA101;
CREATE TABLE BRONZE.ERP_CUST_LOCA101(
CID NVARCHAR(50),
COUNTRY NVARCHAR(50)
);

IF OBJECT_ID ('BRONZE.ERP_CUST_PX_CAT_G1V2','U') IS NOT NULL
	DROP TABLE BRONZE.ERP_CUST_PX_CAT_G1V2;
CREATE TABLE BRONZE.ERP_CUST_PX_CAT_G1V2(
ID NVARCHAR(50),
CATEGORY NVARCHAR(50),
SUB_CATEGORY NVARCHAR(50),
MAINTENANCE NVARCHAR(20)
);

GO

EXEC BRONZE.LOAD_BRONZE;
GO
