CREATE OR ALTER PROCEDURE BRONZE.LOAD_BRONZE AS
BEGIN
	DECLARE @STARTTIME DATETIME,@ENDTIME DATETIME;
	BEGIN TRY
		PRINT '*****************************************';
		PRINT 'LOADING BRONZE LAYER';
		PRINT '*****************************************';

		PRINT '-----------------------------------------';
		PRINT 'LOADING CRM FOLDER';
		PRINT '-----------------------------------------';
		SET @STARTTIME = GETDATE();
		PRINT  'TRUNCATING TABLE BRONZE.CRM_CUSTOMER_INFO';
		TRUNCATE TABLE BRONZE.CRM_CUSTOMER_INFO;
		PRINT 'INSERTING DATA INTO BRONZE.CRM_CUSTOMER_INFO';
		BULK INSERT BRONZE.CRM_CUSTOMER_INFO
		FROM 'C:\Users\Asus\OneDrive\Desktop\Data Science\SQL_Projects\RESOURCES\SOURCE_CRM\cust_info.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @ENDTIME = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(second,@STARTTIME,@ENDTIME) AS NVARCHAR) + ' SECONDS';

		SET @STARTTIME = GETDATE();
		PRINT  'TRUNCATING TABLE BRONZE.CRM_PRODUCT_INFO';
		TRUNCATE TABLE BRONZE.CRM_PRODUCT_INFO;
		PRINT 'INSERTING INTO BRONZE.CRM_PRODUCT_INFO';
		BULK INSERT BRONZE.CRM_PRODUCT_INFO
		FROM 'C:\Users\Asus\OneDrive\Desktop\Data Science\SQL_Projects\RESOURCES\SOURCE_CRM\prd_info.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @ENDTIME = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(SECOND,@STARTTIME,@ENDTIME) AS NVARCHAR) + ' SECONDS';


		SET @STARTTIME = GETDATE();
		PRINT  'TRUNCATING TABLE BRONZE.CRM_SALES_INFO';
		TRUNCATE TABLE BRONZE.CRM_SALES_INFO;
		PRINT'INSERTING INTO BRONZE.CRM_SALES_INFO';
		BULK INSERT BRONZE.CRM_SALES_INFO
		FROM 'C:\Users\Asus\OneDrive\Desktop\Data Science\SQL_Projects\RESOURCES\SOURCE_CRM\sales_details.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @ENDTIME = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(SECOND,@STARTTIME,@ENDTIME) AS NVARCHAR) + ' SECONDS';


		PRINT '-----------------------------------------';
		PRINT 'LOADING ERP FOLDER';
		PRINT '-----------------------------------------';


		SET @STARTTIME = GETDATE();
		PRINT  'TRUNCATING TABLE BRONZE.ERP_CUSTAZ12';
		TRUNCATE TABLE BRONZE.ERP_CUSTAZ12;
		PRINT 'INSERTING INTO BRONZE.ERP_CUSTAZ12';
		BULK INSERT BRONZE.ERP_CUSTAZ12
		FROM 'C:\Users\Asus\OneDrive\Desktop\Data Science\SQL_Projects\RESOURCES\SOURCE_ERP\CUST_AZ12.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @ENDTIME = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(SECOND,@STARTTIME,@ENDTIME) AS NVARCHAR) + ' SECONDS';

		SET @STARTTIME = GETDATE();
		PRINT  'TRUNCATING TABLE BRONZE.ERP_CUST_LOCA101';
		TRUNCATE TABLE BRONZE.ERP_CUST_LOCA101;
		PRINT 'INSERTING DATA INTO BRONZE.ERP_CUST_LOCA101'
		BULK INSERT BRONZE.ERP_CUST_LOCA101
		FROM 'C:\Users\Asus\OneDrive\Desktop\Data Science\SQL_Projects\RESOURCES\SOURCE_ERP\LOC_A101.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @ENDTIME = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(SECOND,@STARTTIME,@ENDTIME) AS NVARCHAR) + ' SECONDS';


		SET @STARTTIME = GETDATE();
		PRINT  'TRUNCATING TABLE BRONZE.ERP_CUST_PX_CAT_G1V2';
		TRUNCATE TABLE BRONZE.ERP_CUST_PX_CAT_G1V2;
		PRINT 'INSERTING INTO BRONZE.ERP_CUST_PX_CAT_G1V2';
		BULK INSERT BRONZE.ERP_CUST_PX_CAT_G1V2
		FROM 'C:\Users\Asus\OneDrive\Desktop\Data Science\SQL_Projects\RESOURCES\SOURCE_ERP\PX_CAT_G1V2.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @ENDTIME = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(SECOND,@STARTTIME,@ENDTIME) AS NVARCHAR) + ' SECONDS';


	END TRY
	BEGIN CATCH
	PRINT 'ERROR WHILE LOAADING BRONZE LAYER';
	PRINT 'ERROR = ' + ERROR_MESSAGE();
	PRINT 'ERROR NUMBER = ' + CAST  (ERROR_NUMBER() AS NVARCHAR);
	END CATCH;
	
END;
GO
