CREATE VIEW GOLD.dim_customers AS
SELECT
	ROW_NUMBER() OVER(ORDER BY CI.CUST_ID) AS customer_key,
	CI.CUST_ID AS customer_id,
	CI.CUST_KEY AS customer_number,
	CI.CUST_FIRSTNAME AS firstname,
	CI.CUST_LASTNAME AS lastname,
	LA.COUNTRY  AS country,
	CI.CUST_MARITALSTATUS AS marital_status,
	CASE WHEN  CI.CUST_GENDER != 'N/A' THEN CI.CUST_GENDER
		ELSE COALESCE(CA.GENDER,'N/A')
	END AS gender,
	CA.BDATE AS birthdate,
	CI.CUST_CREATEDATE AS create_date
FROM SILVER.CRM_CUSTOMER_INFO AS CI
LEFT JOIN SILVER.ERP_CUSTAZ12 CA
ON CI.CUST_KEY = CA.CID
LEFT JOIN SILVER.ERP_CUST_LOCA101 LA
ON CI.CUST_KEY = LA.CID

GO

CREATE VIEW GOLD.dim_prod AS
SELECT
	ROW_NUMBER() OVER(ORDER BY PC.PRD_STARTDATE,PC.PRD_KEY) AS product_key,
	PC.PRD_ID AS product_id,
	PC.PRD_KEY AS product_keys,
	PC.PRD_NAME AS product_name,
	PC.CAT_ID AS category_id,
	PE.CATEGORY AS category,
	PE.SUB_CATEGORY AS sub_category,
	PE.MAINTENANCE AS maintenance,
	PC.PRD_COST AS cost,
	PC.PRD_LINE AS line,
	PC.PRD_STARTDATE AS startdate
FROM SILVER.CRM_PRODUCT_INFO PC
LEFT JOIN SILVER.ERP_CUST_PX_CAT_G1V2 PE
ON PC.CAT_ID = PE.ID
WHERE PRD_ENDDATE IS NULL

GO

CREATE VIEW GOLD.fact_sales AS
SELECT
SR.SLS_ORDER_NUM AS order_number,
PR.product_key,
CR.customer_key,
SR.SLS_ORDER_DATE AS order_date,
SR.SLS_SHIPPING_DATE AS shipping_date,
SR.SLS_DUE_DATE AS due_date,
SR.SLS_SALES AS sales,
SR.SLS_QUANTITY AS quantity,
SR.SLS_PRICE AS price
FROM SILVER.CRM_SALES_INFO SR
LEFT JOIN GOLD.dim_prod PR
ON SR.SLS_PRODUCT_KEY = PR.product_keys
LEFT JOIN GOLD.dim_customers CR
ON SR.SLS_CUSTOMER_ID = CR.customer_id;
