IF OBJECT_ID ('SILVER.CRM_CUSTOMER_INFO','U') IS NOT NULL
	DROP TABLE SILVER.CRM_CUSTOMER_INFO;
CREATE TABLE SILVER.CRM_CUSTOMER_INFO(
CUST_ID INT,
CUST_KEY NVARCHAR(50),
CUST_FIRSTNAME NVARCHAR(50),
CUST_LASTNAME NVARCHAR(50),
CUST_MARITALSTATUS NVARCHAR(50),
CUST_GENDER NVARCHAR(50),
CUST_CREATEDATE date,
DWH_CREATE_DATE DATETIME2 DEFAULT GETDATE()
);
IF OBJECT_ID ('SILVER.CRM_PRODUCT_INFO','U') IS NOT NULL
	DROP TABLE SILVER.CRM_PRODUCT_INFO;
CREATE TABLE SILVER.CRM_PRODUCT_INFO(
PRD_ID INT,
CAT_ID NVARCHAR(50),
PRD_KEY NVARCHAR(50),
PRD_NAME NVARCHAR(50),
PRD_COST INT,
PRD_LINE NVARCHAR(50),
PRD_STARTDATE date,
PRD_ENDDATE date,
DWH_CREATE_DATE DATETIME2 DEFAULT GETDATE()
);
IF OBJECT_ID ('SILVER.CRM_SALES_INFO','U') IS NOT NULL
	DROP TABLE SILVER.CRM_SALES_INFO;
CREATE TABLE SILVER.CRM_SALES_INFO(
SLS_ORDER_NUM VARCHAR(50),
SLS_PRODUCT_KEY VARCHAR(50),
SLS_CUSTOMER_ID INT,
SLS_ORDER_DATE DATE,
SLS_SHIPPING_DATE DATE,
SLS_DUE_DATE DATE,
SLS_SALES INT,
SLS_QUANTITY INT,
SLS_PRICE INT,
DWH_CREATE_DATE DATETIME2 DEFAULT GETDATE()
); 
IF OBJECT_ID ('SILVER.ERP_CUSTAZ12','U') IS NOT NULL
	DROP TABLE SILVER.ERP_CUSTAZ12;
CREATE TABLE SILVER.ERP_CUSTAZ12(
CID NVARCHAR(50),
BDATE DATE,
GENDER NVARCHAR(10),
DWH_CREATE_DATE DATETIME2 DEFAULT GETDATE()
);
IF OBJECT_ID ('SILVER.ERP_CUST_LOCA101','U') IS NOT NULL
	DROP TABLE SILVER.ERP_CUST_LOCA101;
CREATE TABLE SILVER.ERP_CUST_LOCA101(
CID NVARCHAR(50),
COUNTRY NVARCHAR(50),
DWH_CREATE_DATE DATETIME2 DEFAULT GETDATE()
);

IF OBJECT_ID ('SILVER.ERP_CUST_PX_CAT_G1V2','U') IS NOT NULL
	DROP TABLE SILVER.ERP_CUST_PX_CAT_G1V2;
CREATE TABLE SILVER.ERP_CUST_PX_CAT_G1V2(
ID NVARCHAR(50),
CATEGORY NVARCHAR(50),
SUB_CATEGORY NVARCHAR(50),
MAINTENANCE NVARCHAR(20),
DWH_CREATE_DATE DATETIME2 DEFAULT GETDATE()
);
