
CREATE OR ALTER PROCEDURE SILVER.LOAD_SILVER AS
BEGIN
	DECLARE @starttime DATETIME, @endtime DATETIME;
	BEGIN TRY

		PRINT '*****************************************';
		PRINT 'LOADING SILVER LAYER';
		PRINT '*****************************************';

		PRINT '-----------------------------------------';
		PRINT 'LOADING CRM FOLDER';
		PRINT '-----------------------------------------';
		PRINT '---TRUNCATING TABLE SILVER.CRM_CUSTOMER_INFO---'
		TRUNCATE TABLE SILVER.CRM_CUSTOMER_INFO;
		PRINT '---INSERTING INTO TABLE SILVER.CRM_CUSTOMER_INFO---'
		
		SET @starttime = GETDATE();

		INSERT INTO SILVER.CRM_CUSTOMER_INFO(
		CUST_ID,
		CUST_KEY,
		CUST_FIRSTNAME,                 --INSERTING INTO SILVER.CRM_CUSTOMER_INFO
		CUST_LASTNAME,
		CUST_MARITALSTATUS,
		CUST_GENDER,
		CUST_CREATEDATE)


		SELECT
		CUST_ID,
		CUST_KEY,
		TRIM(CUST_FIRSTNAME) AS CUST_FIRSTNAME,  --TRIMMING CUSTOMER FIRSTNAME FOR EXTRA SPACES
		TRIM(CUST_LASTNAME) AS CUST_LASTNAME,    --TRIMMING CUSTOMER LASTNAME FOR EXTRA SPACES
		CASE WHEN UPPER(TRIM(CUST_MARITALSTATUS)) = 'M'THEN 'MARRIED' --REMOVING ABBREVIATION'S
			WHEN UPPER(TRIM(CUST_MARITALSTATUS)) = 'S' THEN 'SINGLE'
			ELSE 'N/A'   --REMOVING NULL VALUES WITH N/A
		END CUST_MARITALSTATUS,
		CASE WHEN UPPER(TRIM(CUST_GENDER)) = 'M'THEN 'MALE'   --REMOVING ABBREVIATION'S
			WHEN UPPER(TRIM(CUST_GENDER)) = 'F' THEN 'FEMALE'
			ELSE 'N/A'   --REMOVING NULL VALUES WITH N/A
		END CUST_GENDER,
		CUST_CREATEDATE
		FROM(
			SELECT
			*
			FROM(
				SELECT
				*,
				ROW_NUMBER() OVER(PARTITION BY CUST_ID ORDER BY CUST_CREATEDATE DESC) AS FLAG
				FROM BRONZE.CRM_CUSTOMER_INFO
				WHERE CUST_ID IS NOT NULL      --REMOVING DUPLICATES
				)T WHERE FLAG = 1
			) AS T2;
		SET @endtime = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(second,@starttime,@endtime) AS NVARCHAR) + ' SECONDS';
		

		PRINT '---TRUNCATING TABLE SILVER.CRM_PRODUCT_INFO---'
		TRUNCATE TABLE SILVER.CRM_PRODUCT_INFO;
		PRINT '---INSERTING INTO TABLE SILVER.CRM_PRODUCT_INFO---'

		SET @starttime = GETDATE();

		INSERT INTO SILVER.CRM_PRODUCT_INFO(
		PRD_ID,
		CAT_ID,
		PRD_KEY,
		PRD_NAME,							--INSERTING INTO SILVER.CRM_PRODUCT_INFO
		PRD_COST,
		PRD_LINE,
		PRD_STARTDATE,
		PRD_ENDDATE)
		SELECT
		PRD_ID,
		REPLACE(SUBSTRING(PRD_KEY,1,5),'-','_') AS CAT_ID, --EXTRACTING CAT_ID 
		SUBSTRING(PRD_KEY,7,LEN(PRD_KEY)) AS PRD_KEY,  --EXTRACTING PRD_KEY
		PRD_NAME,
		ISNULL(PRD_COST,0) AS PRD_COST, --REPLACING NULL WITH 0
		CASE WHEN UPPER(TRIM(PRD_LINE)) = 'M' THEN 'MOUNTAIN'
			WHEN UPPER(TRIM(PRD_LINE)) = 'R' THEN 'ROAD'		--REPLACING ABBREVIATION'S
			WHEN UPPER(TRIM(PRD_LINE)) = 'S' THEN 'OTHER SALES'
			WHEN UPPER(TRIM(PRD_LINE)) = 'T' THEN 'TOURING'
			ELSE 'N/A'   -- REPLACING NULL VALUES WITH N/A
		END PRD_LINE,
		CAST(PRD_STARTDATE AS DATE) AS PRD_STARTDATE, -- CASTING INTO DATE
		CAST(DATEADD(DAY,-1,LEAD(PRD_STARTDATE) OVER(PARTITION BY PRD_KEY ORDER BY PRD_STARTDATE)) AS DATE) AS PRD_ENDDATE --CASTING INTO DATE
		FROM BRONZE.CRM_PRODUCT_INFO;
		SET @endtime = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(second,@starttime,@endtime) AS NVARCHAR) + ' SECONDS';


		PRINT '---TRUNCATING TABLE SILVER.CRM_SALES_INFO---'
		TRUNCATE TABLE SILVER.CRM_SALES_INFO;
		PRINT '---INSERTING INTO TABLE SILVER.CRM_SALES_INFO---'

		SET @starttime = GETDATE();

		INSERT INTO SILVER.CRM_SALES_INFO(
		SLS_ORDER_NUM,
		SLS_PRODUCT_KEY,
		SLS_CUSTOMER_ID,
		SLS_ORDER_DATE,
		SLS_SHIPPING_DATE,
		SLS_DUE_DATE,
		SLS_SALES,
		SLS_QUANTITY,
		SLS_PRICE)


		SELECT
		SLS_ORDER_NUM,
		SLS_PRODUCT_KEY,
		SLS_CUSTOMER_ID,
		CASE WHEN SLS_ORDER_DATE = 0 OR LEN(CAST(SLS_ORDER_DATE AS VARCHAR))<>8 THEN NULL
			ELSE TRY_CONVERT(DATE, CAST(SLS_ORDER_DATE AS CHAR(8)), 112)
		END AS SLS_ORDER_DATE,
		CASE WHEN SLS_SHIPPING_DATE = 0 OR LEN(CAST(SLS_SHIPPING_DATE AS VARCHAR))<>8 THEN NULL
			ELSE TRY_CONVERT(DATE, CAST(SLS_SHIPPING_DATE AS CHAR(8)), 112)
		END AS SLS_SHIPPING_DATE,
		CASE WHEN SLS_DUE_DATE = 0 OR LEN(CAST(SLS_DUE_DATE AS VARCHAR))<>8 THEN NULL
			ELSE TRY_CONVERT(DATE, CAST(SLS_DUE_DATE AS CHAR(8)), 112)
		END AS SLS_DUE_DATE,
		CASE WHEN SLS_SALES IS NULL OR SLS_SALES <=0 OR SLS_SALES  != SLS_QUANTITY  * ABS(SLS_PRICE)
				THEN  SLS_QUANTITY * ABS(SLS_PRICE)
			ELSE SLS_SALES
		END AS SLS_SALES,
		CASE WHEN SLS_QUANTITY IS NULL OR SLS_QUANTITY <=0
				THEN  SLS_SALES/NULLIF(ABS(SLS_PRICE),0)
			ELSE SLS_QUANTITY
		END AS SLS_QUANTITY,
		CASE WHEN SLS_PRICE IS NULL OR SLS_PRICE <=0
				THEN  SLS_SALES/NULLIF(SLS_QUANTITY,0)
			ELSE SLS_PRICE
		END AS SLS_PRICE
		FROM BRONZE.CRM_SALES_INFO;
		SET @endtime = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(second,@starttime,@endtime) AS NVARCHAR) + ' SECONDS';

		PRINT '-----------------------------------------';
		PRINT 'LOADING ERP FOLDER';
		PRINT '-----------------------------------------';

		PRINT '---TRUNCATING TABLE SILVER.ERP_CUSTAZ12---'
		TRUNCATE TABLE SILVER.ERP_CUSTAZ12;
		PRINT '---INSERTING INTO TABLE SILVER.ERP_CUSTAZ12---'

		SET @starttime = GETDATE();

		INSERT INTO SILVER.ERP_CUSTAZ12(
		CID,
		BDATE,
		GENDER
		)

		SELECT
		CASE WHEN CID LIKE 'NAS%' THEN SUBSTRING(CID,4,LEN(CID))
			ELSE CID
		END  AS CID,
		CASE WHEN BDATE > GETDATE() THEN NULL
			ELSE BDATE
		END AS BDATE,
		CASE WHEN UPPER(TRIM(GENDER)) IN ('F','FEMALE') THEN 'Female'
			WHEN UPPER(TRIM(GENDER)) IN ('M','MALE') THEN 'Male'
			ELSE 'N/A'
		END AS GENDER
		FROM BRONZE.ERP_CUSTAZ12;
		SET @endtime = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(second,@starttime,@endtime) AS NVARCHAR) + ' SECONDS';


		PRINT '---TRUNCATING TABLE SILVER.ERP_CUST_LOCA101---'
		TRUNCATE TABLE SILVER.ERP_CUST_LOCA101;
		PRINT '---INSERTING INTO TABLE SILVER.ERP_CUST_LOCA101---'

		SET @starttime = GETDATE();

		INSERT INTO SILVER.ERP_CUST_LOCA101(
		CID,
		COUNTRY
		)

		SELECT 
		REPLACE(CID,'-','') AS CID,
		CASE WHEN TRIM(COUNTRY) IN ('US','Usa') THEN 'United States'
			WHEN TRIM(COUNTRY) = 'DE' THEN 'Germany'
			WHEN COUNTRY = '' OR COUNTRY IS NULL THEN 'N/A'
			ELSE TRIM(COUNTRY)
		END COUNTRY
		FROM BRONZE.ERP_CUST_LOCA101;
		SET @endtime = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(second,@starttime,@endtime) AS NVARCHAR) + ' SECONDS';

		PRINT '---TRUNCATING TABLE SILVER.ERP_CUST_PX_CAT_G1V2---'
		TRUNCATE TABLE SILVER.ERP_CUST_PX_CAT_G1V2;
		PRINT '---INSERTING INTO TABLE SILVER.ERP_CUST_PX_CAT_G1V2---'

		SET @starttime = GETDATE();


		INSERT INTO SILVER.ERP_CUST_PX_CAT_G1V2(
		ID,
		CATEGORY,
		SUB_CATEGORY,
		MAINTENANCE
		)

		SELECT
		ID,
		CATEGORY,
		SUB_CATEGORY,
		MAINTENANCE
		FROM BRONZE.ERP_CUST_PX_CAT_G1V2;
		SET @endtime = GETDATE();
		PRINT 'TIME TAKEN :' + CAST(DATEDIFF(second,@starttime,@endtime) AS NVARCHAR) + ' SECONDS';


	END TRY
	BEGIN CATCH
		PRINT 'THERE WAS ERROR WHILE LOADING SILVER LAYER';
		PRINT 'ERROR' + '  ' + ERROR_MESSAGE();
		PRINT 'ERROR NO.' + '  ' + CAST(ERROR_NUMBER() AS VARCHAR); 
	END CATCH
END
GO

EXEC SILVER.LOAD_SILVER;
GO
